name: CD Pipeline

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main         # Optional: deploy automatically on main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          cd codebase/rdicidr-0.1.0
          docker build -t fsl-challenge-app:latest .

      - name: Tag Docker image for ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fsl-challenge:latest
          docker tag fsl-challenge-app:latest $IMAGE_URI

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fsl-challenge:latest
          docker push $IMAGE_URI

      - name: Deploy to ECS Fargate
        run: |
          CLUSTER_NAME="fsl-cluster"
          SERVICE_NAME="fsl-task-service-wy2hrvu8"
          TASK_DEF="fsl-task"
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fsl-challenge:latest
          
          # Register new task definition
          aws ecs register-task-definition \
            --cli-input-json file://ecs-task-definition.json

          # Update ECS service to use new image
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment
