name: CI Pipeline

on:
  pull_request:
    types: [opened, reopened]

jobs:
    CI:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: codebase/rdicidr-0.1.0

      steps:
        - name: Checkoput code
          uses: actions/checkout@v4
          
        - name: Setup Node.js
          uses: actions/checkout@v4
          with:
            node-version: '15.x'
            cache: 'npm'
            cache-dependecy-path : codebase/rdicidr-0.1.0/package-lock.json

        - name: Install dependecies
          run: npm install
          
        - name: Run linter
          run: npm linter

        - name: Run tess
          run: CI=true npm run test
          
        - name: Build application
          run: npm run build  
